on:
  push
jobs:
  ubuntu22:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Update apt repos
        run: sudo apt-get update

      - name: Install base dependencies
        run: sudo apt-get install -y build-essential libfuse2 fonts-noto-color-emoji libdbus-1-dev

      - name: Build webbluetooth dependency
        run: |
          cd api/webbluetooth
          npm install
          npm run build:all
            
