on:
  push
jobs:
  ubuntu22:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update apt repos
        run: sudo apt-get update

      - name: Install base dependencies
        run: sudo apt-get install build-essential libfuse2 fonts-noto-color-emoji libdbus-1-dev

      - name: Build webbluetooth dependency
        run: |
          cd api/webbluetooth
          npm install
          npm run build || npm run build:all || echo "No build or build:all script found"

      - name: updates
        run: ./update.mjs

      